# Generated by Django 4.0.3 on 2022-10-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_posted_by_alter_jobapplied_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Provide location', max_length=255),
        ),
    ]
